# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.6.0"

default_platform :ios

platform :ios do

  # 1
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3
    produce(
      app_name: ‘JenCode’,
      language: 'English',
      app_version: '1.0',
      sku: '123abc'
    )
    # 4
    cert
    # 5
    sigh(force: true)


  end


   desc "Runs all the tests"
  lane :test do
    scan
  end

 desc "Runs for Build“
  lane :build do
 #gym(scheme: “JenCode”, workspace: “JenCode.xcworkspace")
 slather(
  build_directory: "/Users/Shared/Jenkins/Desktop/JenCode",
  input_format: "bah",
  scheme: "JenCode",
  proj: "JenCode.xcodeproj"
)    
  end

 
 #desc "Take screenshots"
  #lane :screenshot do
   # snapshot
 # end


 error do |lane, exception|
  # This block is called if there was an error running a lane.
  end



end